In [38]:
import numpy as np

In [31]:
squaremeter = np.array([200, 190, 180, 170, 160, 150, 140, 130, 120, 110])
rooms = np.array([5, 5, 4, 4, 4, 3, 3, 3, 2, 2])
price= np.array([100000, 95000, 90000, 85000, 80000, 75000, 70000, 65000, 60000, 55000])

In [32]:
houses = np.array([squaremeter, rooms, price])
print(houses)

[[   200    190    180    170    160    150    140    130    120    110]
 [     5      5      4      4      4      3      3      3      2      2]
 [100000  95000  90000  85000  80000  75000  70000  65000  60000  55000]]


In [33]:
features=houses.transpose()
print(features)

[[   200      5 100000]
 [   190      5  95000]
 [   180      4  90000]
 [   170      4  85000]
 [   160      4  80000]
 [   150      3  75000]
 [   140      3  70000]
 [   130      3  65000]
 [   120      2  60000]
 [   110      2  55000]]


In [34]:
features.shape

(10, 3)

In [35]:
#it means the array has two dimension
#the array has 10 rows and 3 columns

In [59]:
row=int(input("Enter the number of rows"))
column=int(input("Enter the number of columns"))

def make_array(x, y):
    a=np.full((x,y),1)
    for i in range(x):
        for j in range(y):
            if i%2!=0 and j%2!=0:
                a[i][j]=0
    return (print(a))

make_array(row,column)


Enter the number of rows 6
Enter the number of columns 5


[[1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 1 1]
 [1 0 1 0 1]]
