In [55]:
import numpy as np

In [56]:
sample=np.load("earthquakes_sample.npy")
sample

array([['1', '1', '1', '1', '1'],
       ['0', '36.8578', '44.4161', '16.97', '4.0'],
       ['0', '37.4341', '35.852', '7.02', '4.1'],
       ['0', '37.6878', '37.4016', '10.27', '4.4'],
       ['0', '37.2003', '30.4376', '78.07', '4.0'],
       ['0', '35.6846', '26.7266', '42.77', '4.5'],
       ['0', '36.4171', '28.6991', '14.86', '4.1'],
       ['0', '36.0535', '31.2135', '36.68', '5.2'],
       ['0', '37.1958', '30.6241', '50.33', '4.8'],
       ['0', '36.9653', '27.7633', '6.93', '4.3'],
       ['0', '38.893', '26.4483', '11.62', '4.2'],
       ['0', '37.3773', '36.3855', '10.53', '4.8'],
       ['0', '35.8861', '26.0695', '28.49', '4.9'],
       ['0', '37.4635', '36.3113', '15.29', '4.3'],
       ['0', '37.0201', '36.0845', '10.0', '4.1'],
       ['0', '37.6546', '26.6698', '4.5', '4.5'],
       ['0', '37.5318', '29.848000000000003', '17.58', '4.6'],
       ['0', '39.0388', '44.1533', '7.52', '4.5'],
       ['0', '38.357', '44.8686', '10.05', '4.1'],
       ['0', '35.7018', '28.

In [69]:
sample1 = np.arange(100,dtype=float).reshape(20,5)
for i in range(len(sample)):
    for j in range(len(sample[0,:])):
         sample1[i,j]=float(sample[i,j])
sample1

array([[ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ],
       [ 0.    , 36.8578, 44.4161, 16.97  ,  4.    ],
       [ 0.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 0.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 0.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 0.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 0.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 0.    , 38.357 , 44

In [70]:
for i in range(len(sample1[0,:])):
    print("Standart deviation of column",i,":", np.std(sample1[:,i]))
    print("Mean of column              ",i,":", np.mean(sample1[:,i]))

Standart deviation of column 0 : 0.21794494717703364
Mean of column               0 : 0.05
Standart deviation of column 1 : 7.937984843036361
Mean of column               1 : 35.371015
Standart deviation of column 2 : 9.210137907974016
Mean of column               2 : 31.456110000000002
Standart deviation of column 3 : 18.64751250837494
Mean of column               3 : 19.336499999999997
Standart deviation of column 4 : 0.8080068069020212
Mean of column               4 : 4.225


In [119]:
sub_column=np.array([1, 25, 25, 10, 4 ])

In [140]:
sample1=sample1-sub_column
sample1

array([[ 0.00000e+00, -2.40000e+01, -2.40000e+01, -9.00000e+00,
        -3.00000e+00],
       [-1.00000e+00,  1.18578e+01,  1.94161e+01,  6.97000e+00,
         0.00000e+00],
       [-1.00000e+00,  1.24341e+01,  1.08520e+01, -2.98000e+00,
         1.00000e-01],
       [-1.00000e+00,  1.26878e+01,  1.24016e+01,  2.70000e-01,
         4.00000e-01],
       [-1.00000e+00,  1.22003e+01,  5.43760e+00,  6.80700e+01,
         0.00000e+00],
       [-1.00000e+00,  1.06846e+01,  1.72660e+00,  3.27700e+01,
         5.00000e-01],
       [-1.00000e+00,  1.14171e+01,  3.69910e+00,  4.86000e+00,
         1.00000e-01],
       [-1.00000e+00,  1.10535e+01,  6.21350e+00,  2.66800e+01,
         1.20000e+00],
       [-1.00000e+00,  1.21958e+01,  5.62410e+00,  4.03300e+01,
         8.00000e-01],
       [-1.00000e+00,  1.19653e+01,  2.76330e+00, -3.07000e+00,
         3.00000e-01],
       [-1.00000e+00,  1.38930e+01,  1.44830e+00,  1.62000e+00,
         2.00000e-01],
       [-1.00000e+00,  1.23773e+01,  1.1385

In [141]:
sample1=sample1*2
sample1

array([[ 0.00000e+00, -4.80000e+01, -4.80000e+01, -1.80000e+01,
        -6.00000e+00],
       [-2.00000e+00,  2.37156e+01,  3.88322e+01,  1.39400e+01,
         0.00000e+00],
       [-2.00000e+00,  2.48682e+01,  2.17040e+01, -5.96000e+00,
         2.00000e-01],
       [-2.00000e+00,  2.53756e+01,  2.48032e+01,  5.40000e-01,
         8.00000e-01],
       [-2.00000e+00,  2.44006e+01,  1.08752e+01,  1.36140e+02,
         0.00000e+00],
       [-2.00000e+00,  2.13692e+01,  3.45320e+00,  6.55400e+01,
         1.00000e+00],
       [-2.00000e+00,  2.28342e+01,  7.39820e+00,  9.72000e+00,
         2.00000e-01],
       [-2.00000e+00,  2.21070e+01,  1.24270e+01,  5.33600e+01,
         2.40000e+00],
       [-2.00000e+00,  2.43916e+01,  1.12482e+01,  8.06600e+01,
         1.60000e+00],
       [-2.00000e+00,  2.39306e+01,  5.52660e+00, -6.14000e+00,
         6.00000e-01],
       [-2.00000e+00,  2.77860e+01,  2.89660e+00,  3.24000e+00,
         4.00000e-01],
       [-2.00000e+00,  2.47546e+01,  2.2771